AWSTemplateFormatVersion: '2010-09-09'
Description: VPC network ACLs template
Parameters:
  EnvironmentName:
    Description: The name of the environment this is going into (staging, etc)
    Type: String
  VPC:
    Description: The VPC id
    Type: String
  VpcCidrBlock:
    Description: The VPC CIDR block
    Type: String
Resources:
  PrivateNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref 'EnvironmentName'
              - private-subnets
        - Key: Application
          Value: !Ref 'AWS::StackId'
  PrivateInboundFromAllVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PrivateNetworkAcl'
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: !Ref 'VpcCidrBlock'
  PrivateInboundFromAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PrivateNetworkAcl'
      RuleNumber: 110
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: '0.0.0.0/0'
  PrivateOutboundToAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PrivateNetworkAcl'
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: '0.0.0.0/0'
  PrivateOutboundToAllVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PrivateNetworkAcl'
      RuleNumber: 110
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: !Ref 'VpcCidrBlock'
  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - !Ref 'EnvironmentName'
              - public-subnets
        - Key: Application
          Value: !Ref 'AWS::StackId'
  PublicInboundFromAllVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PublicNetworkAcl'
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: !Ref 'VpcCidrBlock'
  PublicInboundFromAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PublicNetworkAcl'
      RuleNumber: 110
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: '0.0.0.0/0'
  PublicOutboundToAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PublicNetworkAcl'
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: '0.0.0.0/0'
  PublicOutboundToAllVPC:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref 'PublicNetworkAcl'
      RuleNumber: 110
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: !Ref 'VpcCidrBlock'
Outputs:
  PrivateNetworkAcl:
    Description: The private network ACL list ID
    Value: !Ref 'PrivateNetworkAcl'
  PublicNetworkAcl:
    Description: The public network ACL list ID
    Value: !Ref 'PublicNetworkAcl'
