AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 website hosting with CloudFront distribution and custom DNS'

Parameters:
  EnvironmentName:
    Type: String
    Description: The environment name (the SSM prefix path name)
    MaxLength: 10

  HostedZoneName:
    Type: String
    Description: The hosted zone name (e.g., example.com)
  
  HostedZoneId:
    Type: String
    Description: The Route 53 hosted zone ID
  
  ServiceName:
    Type: String
    Description: Service name to include in bucket name

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ServiceName}-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${ServiceName}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Enabled: true
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Aliases:
          - !Sub ${ServiceName}.${HostedZoneName}
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-${ServiceName}-cloudfront'


  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub ${ServiceName}.${HostedZoneName}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub ${ServiceName}.${HostedZoneName}
          HostedZoneId: !Ref HostedZoneId

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub ${ServiceName}.${HostedZoneName}
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  DistributionIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${EnvironmentName}/${ServiceName}/DistributionId"
      Type: String
      Value: !GetAtt CloudFrontDistribution.Id
      Description: CloudFront distribution ID for the website

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref WebsiteBucket
  
  WebsiteURL:
    Description: Website URL
    Value: !GetAtt WebsiteBucket.WebsiteURL
  
  CloudFrontURL:
    Description: CloudFront distribution URL
    Value: !GetAtt CloudFrontDistribution.DomainName
  
  CustomDomainURL:
    Description: Custom domain URL
    Value: !Sub 'https://${HostedZoneName}'
