name: Setup Poetry
description: Install and setup Poetry & Earthmover
inputs:
  working-dir:
    description: The application build directory
    required: true
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install poetry
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: |
        python -m pip install poetry==1.8.3
        python -m pip install earthmover
        python -m poetry config virtualenvs.in-project true

    - name: Cache the virtualenv
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

