name: Build and Push
description: Build and Push a Docker Image to AWS ECR
inputs:
  working-dir:
    description: The application build directory
    required: true
  github-actions-role:
    description: The AWS role to assume for GitHub Actions
    required: true
  role-session-name:
    description: The session tag to apply to the role session
    required: true
  aws-region:
    description: The AWS region of the target ECR registry
    required: true
  ecr-repository:
    description: The target ECR repo within the ECR registry
    required: true
  build-args:
    description: Docker build arguments (optional)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        audience: sts.amazonaws.com
        role-to-assume: ${{ inputs.github-actions-role }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: image tag
      id: vars
      shell: bash
      run: |
        sha_short=$(git rev-parse --short HEAD)
        date_string=$(date +%Y-%m-%d-%H-%M-%S)
        tag=${date_string}-${sha_short}
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.working-dir }}
        platforms: linux/amd64
        build-args: ${{ inputs.build-args }}
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ steps.vars.outputs.tag }}
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:latest
        cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:latest
        cache-to: type=inline
