FROM python:3.13-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY projects/dagster_docker_compose/dagster.yaml $DAGSTER_HOME
COPY projects/dagster_docker_compose/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME